const data = {
	AvailableCourses: [
		{
			id: 109406,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11484',
			course_number: '5210',
			subject: 'MBA',
			subject_description: 'MBA',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: 'OL1',
			campus: 'Online',
			schedule_type: 'Lecture',
			course_title: 'Personal Development, Ethics, and Social Responsibility',
			credits: 3,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Diego Arias',
			instructor_email: 'ariasdi@udmercy.edu',
			building: 'Online',
			room: 'ONLINE',
			start_time: '1840',
			end_time: '2110',
			monday: 1,
			tuesday: 0,
			wednesday: 0,
			thursday: 0,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'ONL1',
			instructional_method_description: 'Online 100%'
		},
		{
			id: 109417,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11495',
			course_number: '4590',
			subject: 'BUS',
			subject_description: 'Business Administration',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Social Entrepreneurship',
			credits: 3,
			max_enrollment: 24,
			enrolled: 0,
			seats_available: 24,
			instructor: 'Ram Kesavan',
			instructor_email: 'kesavar@udmercy.edu',
			building: 'Commerce &amp; Finance',
			room: '238',
			start_time: '1530',
			end_time: '1645',
			monday: 0,
			tuesday: 1,
			wednesday: 0,
			thursday: 1,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'HYB2',
			instructional_method_description: 'Hybrid 51-74%'
		},
		{
			id: 109429,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11502',
			course_number: '1500',
			subject: 'PHL',
			subject_description: 'Philosophy',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Critical Thinking',
			credits: 3,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Juan Carlos Flores',
			instructor_email: 'floresju@udmercy.edu',
			building: null,
			room: null,
			start_time: '1120',
			end_time: '1235',
			monday: 0,
			tuesday: 1,
			wednesday: 0,
			thursday: 1,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		},
		{
			id: 109445,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11503',
			course_number: '7990',
			subject: 'CIVE',
			subject_description: 'Civil Engineering',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '02',
			campus: 'McNichols Campus',
			schedule_type: 'Research/Thesis/Dissertation',
			course_title: 'Civil Engineering Doctoral Dissertation',
			credits: 0,
			max_enrollment: 0,
			enrolled: 0,
			seats_available: 0,
			instructor: 'Alan Hoback',
			instructor_email: 'hobackas@udmercy.edu',
			building: null,
			room: null,
			start_time: '1940',
			end_time: '2210',
			monday: 1,
			tuesday: 0,
			wednesday: 0,
			thursday: 0,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'DIRE',
			instructional_method_description: 'Directed Study/Research'
		},
		{
			id: 109451,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11507',
			course_number: '4480',
			subject: 'HIS',
			subject_description: 'History',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Racial Violence &amp; Comm Memory',
			credits: 0,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Roy Finkenbine',
			instructor_email: 'finkenre@udmercy.edu',
			building: 'Briggs',
			room: '301',
			start_time: '1600',
			end_time: '1830',
			monday: 1,
			tuesday: 0,
			wednesday: 0,
			thursday: 0,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		},
		{
			id: 109452,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11508',
			course_number: '3000',
			subject: 'CAS',
			subject_description: 'Catholic Studies',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Catholic Church History: Crystallizing Moments',
			credits: 3,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Gregory Banazak',
			instructor_email: 'banazaga@udmercy.edu',
			building: null,
			room: null,
			start_time: '1600',
			end_time: '1830',
			monday: 1,
			tuesday: 0,
			wednesday: 0,
			thursday: 0,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		},
		{
			id: 109453,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11509',
			course_number: '3530',
			subject: 'CAS',
			subject_description: 'Catholic Studies',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '02',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Dynamics of Spiritual Growth',
			credits: 3,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Michael Hovey',
			instructor_email: 'hoveymw@udmercy.edu',
			building: null,
			room: null,
			start_time: '1000',
			end_time: '1050',
			monday: 1,
			tuesday: 0,
			wednesday: 1,
			thursday: 0,
			friday: 1,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		},
		{
			id: 109454,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11510',
			course_number: '3530',
			subject: 'CAS',
			subject_description: 'Catholic Studies',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Dynamics of Spiritual Growth',
			credits: 3,
			max_enrollment: 35,
			enrolled: 0,
			seats_available: 35,
			instructor: 'Si Hendry SJ',
			instructor_email: 'hendrysi@udmercy.edu',
			building: null,
			room: null,
			start_time: '0830',
			end_time: '0945',
			monday: 0,
			tuesday: 1,
			wednesday: 0,
			thursday: 1,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		},
		{
			id: 109455,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11511',
			course_number: '2000',
			subject: 'CAS',
			subject_description: 'Catholic Studies',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Catholicism: Spirit and Methods',
			credits: 3,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Si Hendry SJ',
			instructor_email: 'hendrysi@udmercy.edu',
			building: null,
			room: null,
			start_time: '1120',
			end_time: '1235',
			monday: 0,
			tuesday: 1,
			wednesday: 0,
			thursday: 1,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		},
		{
			id: 109465,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11513',
			course_number: '1120',
			subject: 'CHM',
			subject_description: 'Chemistry',
			pre_requisite: 'CHM 1080,C, and, CHM 1150,D',
			next_pre_requisite: 8,
			section: '05',
			campus: 'McNichols Campus',
			schedule_type: 'Lab',
			course_title: 'Inorganic and Analytical Chemistry Laboratory',
			credits: 1,
			max_enrollment: 24,
			enrolled: 0,
			seats_available: 24,
			instructor: '',
			instructor_email: '',
			building: null,
			room: null,
			start_time: '0800',
			end_time: '0850',
			monday: 1,
			tuesday: 0,
			wednesday: 0,
			thursday: 0,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		}
	],
	Schedule: [
		{
			id: 109406,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11484',
			course_number: '5210',
			subject: 'MBA',
			subject_description: 'MBA',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: 'OL1',
			campus: 'Online',
			schedule_type: 'Lecture',
			course_title: 'Personal Development, Ethics, and Social Responsibility',
			credits: 3,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Diego Arias',
			instructor_email: 'ariasdi@udmercy.edu',
			building: 'Online',
			room: 'ONLINE',
			start_time: '1840',
			end_time: '1910',
			monday: 1,
			tuesday: 0,
			wednesday: 0,
			thursday: 0,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'ONL1',
			instructional_method_description: 'Online 100%'
		},
		{
			id: 109417,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11495',
			course_number: '4590',
			subject: 'BUS',
			subject_description: 'Business Administration',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Social Entrepreneurship',
			credits: 3,
			max_enrollment: 24,
			enrolled: 0,
			seats_available: 24,
			instructor: 'Ram Kesavan',
			instructor_email: 'kesavar@udmercy.edu',
			building: 'Commerce &amp; Finance',
			room: '238',
			start_time: '1530',
			end_time: '1645',
			monday: 0,
			tuesday: 1,
			wednesday: 0,
			thursday: 1,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'HYB2',
			instructional_method_description: 'Hybrid 51-74%'
		},
		{
			id: 109429,
			term: '202610',
			term_description: 'Fall 2025',
			crn: '11502',
			course_number: '1500',
			subject: 'PHL',
			subject_description: 'Philosophy',
			pre_requisite: 'None',
			next_pre_requisite: 0,
			section: '01',
			campus: 'McNichols Campus',
			schedule_type: 'Lecture',
			course_title: 'Critical Thinking',
			credits: 3,
			max_enrollment: 30,
			enrolled: 0,
			seats_available: 30,
			instructor: 'Juan Carlos Flores',
			instructor_email: 'floresju@udmercy.edu',
			building: null,
			room: null,
			start_time: '0920',
			end_time: '1235',
			monday: 0,
			tuesday: 1,
			wednesday: 0,
			thursday: 1,
			friday: 0,
			saturday: 0,
			sunday: 0,
			start_date: '08/25/2025',
			end_date: '12/13/2025',
			instructional_method: 'TRAD',
			instructional_method_description: 'Traditional'
		}
	]
};

module.exports = { data };